import Link from "next/link";
import { Nav, Footer } from "./components";
import { projects, projectLogs, essays, deepDives, formatDate } from "./content";

export default function Home() {
  return <main><Nav />
    <section className="hero shell"><p className="kicker">Applied AI engineer · Builder · Writer</p><h1>I turn deep domain knowledge into <em>intelligent products.</em></h1><div className="heroBottom"><p>Hi, I&apos;m Armstrong. I build software that helps domain experts encode their knowledge into useful AI products.</p><div className="heroActions"><a className="button dark" href="#work">Explore my work ↓</a><a className="textLink" href="mailto:armstrongolusoji9@gmail.com">Discuss a project ↗</a></div></div><div className="heroMark" aria-hidden="true">A<span>/</span>O</div></section>
    <section className="thesis"><div className="shell thesisGrid"><p className="sectionLabel">01 / The thesis</p><div><h2>The internet is moving from the creator economy to the <em>curator economy.</em></h2><p>The best digital products of the next decade will help users find and act on information specific to their context. AI co-pilots are the interface. Domain experts will make it happen by encoding their knowledge into products that drive niche results.</p></div><p className="marginNote">That is the future I am betting the next decade of my life on.</p></div></section>
    <section className="work shell" id="work"><header className="sectionHead"><div><p className="sectionLabel">02 / Active projects</p><h2>Products built around <em>real expertise.</em></h2></div><Link className="textLink" href="/projects">View all projects ↗</Link></header><div className="projectGrid">{projects.map((project, index) => <Link className={`projectCard tone-${index + 1}`} href={`/projects/${project.slug}`} key={project.slug}><div className="cardTop"><span>{String(index + 1).padStart(2, "0")}</span><span className="status">{String(project.meta.status)} · {String(project.meta.year)}</span></div><p className="eyebrow">{String(project.meta.role)}</p><h3>{project.title}</h3><p>{project.description}</p><div className="tags">{(project.meta.stack as string[] || []).map((tag) => <span key={tag}>{tag}</span>)}</div><div className="cardLink">View project <span>↗</span></div></Link>)}</div></section>
    <section className="technicalBand"><div className="shell technicalGrid"><div><p className="sectionLabel light">03 / Under the hood</p><h2>Engineering is philosophy turned into <em>proof of work.</em></h2></div><div className="diveList">{deepDives.map((dive) => <Link href={`/technical/${dive.slug}`} key={dive.slug}><span className="lambda">λ</span><div><p>{(dive.meta.stack as string[] || []).join(" · ")}</p><h3>{dive.title}</h3><small>{dive.meta.difficulty as string} · {formatDate(dive.date)}</small></div><b>↗</b></Link>)}<Link className="allDives" href="/technical">Browse technical deep dives →</Link></div></div></section>
    <section className="writing shell"><header className="sectionHead"><div><p className="sectionLabel">04 / Essays and project logs</p><h2>Thinking in public.</h2></div><Link className="textLink" href="/writing">Read the complete archive ↗</Link></header><div className="essayList">{[...projectLogs, ...essays].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map((item, i) => <Link href={item.type==="projectLog"?`/writing/project/${item.slug}`:`/writing/${item.slug}`} key={`${item.type}-${item.slug}`}><span className="essayNo">{String(i+1).padStart(2,"0")}</span><h3>{item.title}</h3><p>{item.type === "projectLog" ? String(item.meta.project) : "Essay"}</p><time>{formatDate(item.date)}</time><b>↗</b></Link>)}</div></section>
    <section className="contact"><div className="shell contactInner"><p className="sectionLabel light">05 / Let&apos;s work</p><h2>Have a hard AI problem worth <em>solving well?</em></h2><p>I am open to select consulting and build engagements in Applied AI.</p><a className="button paper" href="mailto:armstrongolusoji9@gmail.com">Tell me what you are building ↗</a></div></section><Footer />
  </main>;
}
